apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: microgateway
  name: microgateway
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: microgateway
    spec:
      containers:
      - name: microgateway
        ports:
        - containerPort: 4000
        resources: {}
      restartPolicy: Always
status: {}
