apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: nginx
  name: nginx
spec:
  ports:
  - name: "4430"
    port: 4430
    targetPort: 443
  selector:
    io.kompose.service: nginx
status:
  loadBalancer: {}
