version: '3'

services:

 client:
  build: ./client
  depends_on:
    - jenkins
    
 jenkins:
  build: ./jenkins
  ports:
    - "8080:8080"
  depends_on:
    - gitlab
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock