version: '3'

services:

 client:
  build: ./client
  depends_on:
    - jenkins
    
 jenkins:
  build: ./jenkins
  ports:
    - "8080:8080"
  depends_on:
    - gitlab
  volumes:
    - /var/run/docker.sock:/var/run/docker.sock

 gitlab:
  image: gitlab/gitlab-ce:8.16.7-ce.0
  restart: always
  environment:
    GITLAB_OMNIBUS_CONFIG: |
      external_url 'http://gitlab/'
      # Add any other gitlab.rb configuration here, each on its own line
  ports:
    - "8000:80"